// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3WUVkbZVX0AHr4Ubch5QcUV5bJJ7LDmU',
    appId: '1:117015222775:web:cb1dcf98e9976692e9b6f2',
    messagingSenderId: '117015222775',
    projectId: 'qr-scanner-e4d20',
    authDomain: 'qr-scanner-e4d20.firebaseapp.com',
    storageBucket: 'qr-scanner-e4d20.firebasestorage.app',
    measurementId: 'G-HSN1BE3K3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHZ2eugNN0VQxxUJGiMfGNdaXK8uEE_jI',
    appId: '1:117015222775:android:533ac8f86028caebe9b6f2',
    messagingSenderId: '117015222775',
    projectId: 'qr-scanner-e4d20',
    storageBucket: 'qr-scanner-e4d20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYm10ekv2xWsWSRhEdXnSRPN5iUlhB274',
    appId: '1:117015222775:ios:2109ba0079bd4d10e9b6f2',
    messagingSenderId: '117015222775',
    projectId: 'qr-scanner-e4d20',
    storageBucket: 'qr-scanner-e4d20.firebasestorage.app',
    iosBundleId: 'com.example.qrScanner',
  );
}
